package Dailu;

public class Empleados {

	// Declaramos los atributos
	public int idEmpleado;
	public int DNI;
	public String nombre;
	public String apellido;
	public int numeroDepartamento;

	// Declaramos el metodo constructor sin parámetros
	public Empleados() {
	}

	// Declaramos el metodo constructor con parámetros
	public Empleados(int idEmpleado, int DNI, String nombre, String apellido, int numeroDepartamento) {
		this.idEmpleado = idEmpleado;
		this.DNI = DNI;
		this.nombre = nombre;
		this.apellido = apellido;
		this.numeroDepartamento = numeroDepartamento;
	}

	// Declaramos los setters y getters
	public int getIdEmpleado() {
		return idEmpleado;
	}

	// Autogenerated Setters & Getters: Source -> Generate Getters and Setters
	public void setIdEmpleado(int idEmpleado) {
		this.idEmpleado = idEmpleado;
	}

	public int getDNI() {
		return DNI;
	}

	public void setDNI(int dNI) {
		DNI = dNI;
	}

	public String getNombre() {
		return nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellido() {
		return apellido;
	}

	public void setApellido(String apellido) {
		this.apellido = apellido;
	}

	public int getNumeroDepartamento() {
		return numeroDepartamento;
	}

	public void setNumeroDepartamento(int numeroDepartamento) {
		this.numeroDepartamento = numeroDepartamento;
	}

}
